In [1]:
import pandas as pd
import numpy as np

from market_data import MarketData
from data_processor import DataProcessor
from calculate_indicators import Calculate
from trading_strategy import TradingStrategy

# **1. Download Data**

In [2]:
tickers = [
    # Technology (Công nghệ)
    "AAPL","MSFT","GOOGL","AMZN","META",
    "NVDA","AMD","INTC","AVGO",
    "ADBE","CRM","ORCL","IBM",
    "SAP","ASML","QCOM","TXN",
    "UBER","SHOP","XYZ","NFLX","SONY",
    "INTU","ADSK","SNOW",

    # Financials (Tài chính – ngân hàng – đầu tư)
    "JPM","BAC","WFC","C",
    "GS","MS","BRK-A","BRK-B",
    "V","MA","PYPL","AXP",
    "SCHW","BLK","HSBC","RY",
    "CME","BK",

    # Consumer (Tiêu dùng – bán lẻ – giải trí)
    "WMT","COST","HD","TGT",
    "MCD","SBUX","KO","PEP",
    "PG","UL","DEO","PM",
    "NKE","DIS","CMG","TSM",
    "EA","TTWO","RBLX",
    "MGM","YUM",

    # Industrials (Công nghiệp – vận tải – quốc phòng)
    "CAT","DE","BA","LMT",
    "UPS","FDX","GE","HON",
    "MMM","RTX","NOC","GD",
    "EMR",

    # Energy & Materials (Năng lượng – nguyên vật liệu)
    "XOM","CVX","BP","SHEL",
    "COP","SLB","HAL","EOG",
    "LIN","APD","SHW","FCX","NUE",

    # Healthcare (Y tế – dược phẩm – bảo hiểm y tế)
    "JNJ","PFE","MRK","ABT","ABBV",
    "UNH","CVS","TMO","BMY","AMGN"
]

len(tickers)

100

In [3]:
market = MarketData(tickers)
market.download_data(start_date = "2010-01-01", end_date = "2025-10-11")

[*********************100%***********************]  100 of 100 completed

Price        Adj Close                                                  \
Ticker            AAPL        ABBV         ABT        ADBE        ADSK
Date
2010-01-04    6.418384         NaN   18.414780   37.090000   25.670000
2010-01-05    6.429481         NaN   18.266005   37.700001   25.280001
2010-01-06    6.327210         NaN   18.367443   37.619999   25.340000
2010-01-07    6.315514         NaN   18.519609   36.889999   25.480000
2010-01-08    6.357502         NaN   18.614285   36.689999   26.260000
...                ...         ...         ...         ...         ...
2025-10-06  256.441406  228.542419  133.147934  350.140015  323.429993
2025-10-07  256.231628  231.163513  132.431122  348.309998  314.190002
2025-10-08  257.810089  229.584900  133.675583  348.769989  311.410004
2025-10-09  253.793961  229.038834  132.719818  347.470001  310.320007
2025-10-10  245.032471  228.850189  131.983109  337.510010  303.500000

Price                                                                    ...  \
Ticker             AMD        AMGN        AMZN         APD         ASML  ...
Date                                                                     ...
2010-01-04    9.700000   39.311676    6.695000   51.808655    32.425724  ...
2010-01-05    9.710000   38.971157    6.734500   51.378765    32.678318  ...
2010-01-06    9.570000   38.678272    6.612500   50.955128    32.977695  ...
2010-01-07    9.470000   38.324116    6.500000   50.662323    32.060860  ...
2010-01-08    9.430000   38.664665    6.676000   50.986271    31.293728  ...
...                ...         ...         ...         ...          ...  ...
2025-10-06  203.710007  292.037079  220.899994  270.950012  1041.452271  ...
2025-10-07  211.509995  293.447021  221.779999  270.890015  1000.524902  ...
2025-10-08  235.559998  292.533539  225.220001  268.579987   986.060547  ...
2025-10-09  232.889999  293.337799  227.740005  262.709991   978.803406  ...
2025-10-10  214.899994  288.075348  216.369995  257.079987   934.531982  ...

Price           Volume                                                   \
Ticker            UBER       UL       UNH       UPS         V       WFC
Date
2010-01-04         NaN   799200  12199500   3897200  20180000  39335700
2010-01-05         NaN   929500  11180700   5966300  25833600  55416000
2010-01-06         NaN  1811600   9761100   5770200  16254000  33237000
2010-01-07         NaN  1365300  11789800   5747000  27841200  61649000
2010-01-08         NaN   761700   7228700  13779300  11907200  35508700
...                ...      ...       ...       ...       ...       ...
2025-10-06  22760900.0  2028600   7181700   6987000   4735600  12837700
2025-10-07  12583600.0  2186600   7236200   4726800   5044600  10371300
2025-10-08  10071200.0  1821300   9438300   4896000   3927500  11277400
2025-10-09  13435700.0  2520000   8759800   5784700   4434800   8432200
2025-10-10  17021100.0  5310800  13141900   8506000   6296200  16004300

Price
Ticker           WMT       XOM        XYZ      YUM
Date
2010-01-04  62259300  27809100        NaN  2962274
2010-01-05  46945200  30174700        NaN  3298757
2010-01-06  37551600  35044700        NaN  4178981
2010-01-07  31988100  27192100        NaN  2452472
2010-01-08  34089600  24891800        NaN  3772392
...              ...       ...        ...      ...
2025-10-06  13303600  12036800  5324100.0  1395000
2025-10-07  15538900  11945000  5428000.0  1657100
2025-10-08  13584100  12301000  6024900.0  1150600
2025-10-09  19508000  10976200  4193600.0  1371000
2025-10-10  18519400  13811600  8802300.0  2055300

[3968 rows x 600 columns]

In [4]:
market.save_df(filename='price_volume_data.csv')

# **2. Data Preparation and Outlier Handling**

In [2]:
data = pd.read_csv("price_volume_data.csv", header=[0, 1], index_col=0, parse_dates=True)
data.head()

Price      Adj Close                                                         \
Ticker          AAPL ABBV        ABT       ADBE       ADSK   AMD       AMGN
Date
2010-01-04  6.418384  NaN  18.414780  37.090000  25.670000  9.70  39.311676
2010-01-05  6.429481  NaN  18.266005  37.700001  25.280001  9.71  38.971157
2010-01-06  6.327210  NaN  18.367443  37.619999  25.340000  9.57  38.678272
2010-01-07  6.315514  NaN  18.519609  36.889999  25.480000  9.47  38.324116
2010-01-08  6.357502  NaN  18.614285  36.689999  26.260000  9.43  38.664665

Price                                     ... Volume                     \
Ticker        AMZN        APD       ASML  ...   UBER       UL       UNH
Date                                      ...
2010-01-04  6.6950  51.808655  32.425724  ...    NaN   799200  12199500
2010-01-05  6.7345  51.378765  32.678318  ...    NaN   929500  11180700
2010-01-06  6.6125  50.955128  32.977695  ...    NaN  1811600   9761100
2010-01-07  6.5000  50.662323  32.060860  ...    NaN  1365300  11789800
2010-01-08  6.6760  50.986271  31.293728  ...    NaN   761700   7228700

Price
Ticker           UPS         V       WFC       WMT       XOM XYZ      YUM
Date
2010-01-04   3897200  20180000  39335700  62259300  27809100 NaN  2962274
2010-01-05   5966300  25833600  55416000  46945200  30174700 NaN  3298757
2010-01-06   5770200  16254000  33237000  37551600  35044700 NaN  4178981
2010-01-07   5747000  27841200  61649000  31988100  27192100 NaN  2452472
2010-01-08  13779300  11907200  35508700  34089600  24891800 NaN  3772392

[5 rows x 600 columns]

In [3]:
prepare = DataProcessor("price_volume_data.csv")
prepare.add_missing_dates()

# for ticker in prepare.tickers:
#     prepare.check_na(ticker)

prepare.add_log_returns()

prepare.drop_na()
prepare.winsorize_data()

prepare.save_cleaned_data("cleaned_price_volume_data.csv")

# for ticker in tickers:
#     prepare.draw_boxplot(ticker, 'Return')

# for ticker in tickers:
#     prepare.draw_histogram(ticker, 'Return')

Số lượng missing dates: 147
Missing dates:
 DatetimeIndex(['2010-01-18', '2010-02-15', '2010-04-02', '2010-05-31',
               '2010-07-05', '2010-09-06', '2010-11-25', '2010-12-24',
               '2011-01-17', '2011-02-21',
               ...
               '2024-12-25', '2025-01-01', '2025-01-09', '2025-01-20',
               '2025-02-17', '2025-04-18', '2025-05-26', '2025-06-19',
               '2025-07-04', '2025-09-01'],
              dtype='datetime64[ns]', length=147, freq=None)

In [4]:
c = Calculate("cleaned_price_volume_data.csv")
c.add_indicators()

c.df.to_csv("price_volume_indicators_data.csv")

# c.calculate_position_size()

print(set(c.df.columns.get_level_values(0)))
c.df.tail()

{'Close', 'Adj Close', 'High', 'Volatility', 'Volume', 'Open', 'Log Return', 'Low', 'SMA_50', 'SMA_200'}

             Adj Close                                                  \
Ticker            AAPL        ABBV         ABT        ADBE        ADSK
2025-10-06  256.441406  228.542419  133.147934  350.140015  323.429993
2025-10-07  256.231628  231.163513  132.431122  348.309998  314.190002
2025-10-08  257.810089  229.584900  133.675583  348.769989  311.410004
2025-10-09  253.793961  229.038834  132.719818  347.470001  310.320007
2025-10-10  245.032471  228.850189  131.983109  337.510010  303.500000

                                                                         ...  \
Ticker             AMD        AMGN        AMZN         APD         ASML  ...
2025-10-06  203.710007  292.037079  220.899994  270.950012  1041.452271  ...
2025-10-07  211.509995  293.447021  221.779999  270.890015  1000.524902  ...
2025-10-08  235.559998  292.533539  225.220001  268.579987   986.060547  ...
2025-10-09  232.889999  293.337799  227.740005  262.709991   978.803406  ...
2025-10-10  214.899994  288.075348  216.369995  257.079987   934.531982  ...

           Volatility                                                    \
Ticker           UBER        UL       UNH       UPS         V       WFC
2025-10-06   0.323777  0.114899  0.215691  0.158889  0.186439  0.168176
2025-10-07   0.316669  0.116156  0.214581  0.158124  0.187998  0.168784
2025-10-08   0.318220  0.110913  0.207018  0.158309  0.188144  0.166671
2025-10-09   0.338020  0.114522  0.208329  0.162004  0.182901  0.165641
2025-10-10   0.351963  0.125074  0.219998  0.182124  0.178789  0.187795


Ticker           WMT       XOM       XYZ       YUM
2025-10-06  0.138153  0.191584  0.329469  0.183706
2025-10-07  0.125544  0.191213  0.331345  0.177543
2025-10-08  0.126148  0.190642  0.340763  0.170477
2025-10-09  0.114416  0.186059  0.327480  0.182805
2025-10-10  0.094926  0.197964  0.397948  0.167664

[5 rows x 1000 columns]

# **3. Trading Strategy**

In [5]:
strategy = TradingStrategy("price_volume_indicators_data.csv")
print(set(strategy.df.columns.get_level_values(0)))

{'Close', 'Adj Close', 'High', 'Volatility', 'Volume', 'Open', 'Log Return', 'Low', 'SMA_50', 'SMA_200'}

## **3.1. Momentum Strategy**

In [6]:
strategy.momentum_signal()
strategy.apply_position_sizing()

In [7]:
strategy.get_top_portfolio()

Ngày giao dịch: 2025-10-10

  Ticker       Price  Volatility Action  Shares         Value
0     RY  143.639999    0.092477   LONG      75  10772.999954
1    WMT  101.839996    0.094926   LONG     103  10489.519623
2    JPM  300.890015    0.119291   LONG      27   8124.030396
3    LMT  501.244415    0.127377   LONG      15   7518.666229
4    JNJ  189.516724    0.132111   LONG      39   7391.152222
5     HD  375.750000    0.097521  SHORT     -27  10145.250000
6  BRK-B  489.130005    0.098613  SHORT     -20   9782.600098
7     KO   66.572411    0.119880  SHORT    -125   8321.551323
8    HON  188.231689    0.119342  SHORT     -44   8282.194336
9    DIS  109.190002    0.121242  SHORT     -75   8189.250183

## **3.2. Mean Reversion Strategy**

In [8]:
strategy.mean_reversion_signal()
strategy.apply_position_sizing()

d:\CODE\PYTHON\CF\trading_strategy.py:52: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  self.df = self.df.drop(columns=['Signal'])
d:\CODE\PYTHON\CF\trading_strategy.py:78: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  self.df = self.df.drop(columns=['Position Size'])

In [10]:
strategy.get_top_portfolio(top_n=10)

Ngày giao dịch: 2025-10-10

   Ticker       Price  Volatility Action  Shares         Value
0      RY  143.639999    0.092477   LONG      75  10772.999954
1     HON  188.231689    0.119342   LONG      44   8282.194336
2     DIS  109.190002    0.121242   LONG      75   8189.250183
3     JPM  300.890015    0.119291   LONG      27   8124.030396
4     LIN  453.820007    0.143880   LONG      15   6807.300110
5     BAC   48.650002    0.147086   LONG     139   6762.350212
6     CVX  147.255386    0.163652   LONG      41   6037.470840
7     YUM  140.952499    0.167664   LONG      42   5920.004974
8      DE  446.350006    0.165906   LONG      13   5802.550079
9      MS  150.941086    0.173668   LONG      38   5735.761261
10    PEP  150.080002    0.167652  SHORT     -39   5853.120071